### ISSUE TITLE
New category - API Security

### ISSUE THREAD

**Issue by geocine** [yosriady/api-development-tools#11]
Can we add a new category? API Security and under it are tools for Authorization/Authentication in different programming languages . There are also learning resources for these topics.

**Comment by yosriady** [comment]
Absolutely 👍

**Comment by geocine** [comment]
@yosriady this is offtopic as I don't know how to contact you. Do you know a meetup group in Singapore that focuses on API Development? Something like the http://www.apicraft.org/

**Comment by yosriady** [comment]
@geocine Not that I'm aware of - would you like to start one together?

**Comment by geocine** [comment]
@yosriady sure I am with you. I can see you already have experiences in speaking engagements. I haven't done those yet. I am new to Singapore and would like to make friends in the dev community. Also, I have been dabbling with APIs for less than a year and I am pretty obsessed.

**Comment by yosriady** [comment]
@geocine http://www.meetup.com/API-Craft-Singapore

**Comment by geocine** [comment]
@yosriady Thanks I joined

**Comment by yosriady** [comment]
@geocine Feel free to add the new category in a new PR.
