### ISSUE TITLE
How about API framework, PHP, Yii2?

### ISSUE THREAD

**Issue by TomaszKane** [yosriady/api-development-tools#25]
Hi! How about add Yii2 Framework to PHP API Frameworks section?

http://www.yiiframework.com/doc-2.0/guide-rest-quick-start.html

Regards.

**Comment by yosriady** [comment]
@TomaszKane That would be great!

**Comment by TomaszKane** [comment]
Done, https://github.com/yosriady/api-development-tools/pull/27
